# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=1.21
yarn_mappings=1.21+build.9
loader_version=0.15.11

# Fabric API
fabric_version=0.100.8+1.21

# Mod Properties
mod_version=1.2.2-1.21
maven_group=io.github.paomiantong
archives_base_name=slimefun_predicate

# EMI Properties
emi_version=1.1.10+1.21

# Cloth Config Properties
cloth_config_version=15.0.128

# Mod Menu
mod_menu_version=11.0.1

# Loom Properties
loom_libraries_base=https://bmclapi2.bangbang93.com/maven/
loom_resources_base=https://bmclapi2.bangbang93.com/assets/
loom_version_manifests=https://bmclapi2.bangbang93.com/mc/game/version_manifest.json
loom_experimental_versions=https://maven.fabricmc.net/net/minecraft/experimental_versions.json
#loom_fabric_repository=https://repository.hanbings.io/proxy/

# https://projectlombok.org/setup/gradle
lombok_version=1.18.30